language: c++

script:
  - mkdir -p build
  - cd build
  - qmake ../xastir-qt.pro || qmake-qt4 ../xastir-qt.pro || qmake-qt5 ../xastir-qt.pro
  - make
  - sudo make install

matrix:
  include:
    - os: linux
      name: "Ubuntu 14.04 with Qt4"
      addons:
        apt:
          packages:
            - qt4-dev-tools
    - os: linux
      dist: xenial
      name: "Ubuntu 16.04 with Qt5"
      addons:
        apt:
          packages:
            - qtbase5-dev
    - os: osx
      name: "OSX with Qt5"
      addons:
        homebrew:
          packages:
            - qt5
            - brew link qt5 --force


