language: c++

script:
  - mkdir -p build
  - cd build
  - qmake ../xastir-qt.pro || qmake-qt4 ../xastir-qt.pro || qmake-qt5 ../xastir-qt.pro
  - make
  - sudo make install

matrix:
  include:
    - os: linux
      name: "Linux with Qt4"
      addons:
        apt:
          packages:
            - qtbase4-dev
    - os: linux
      dist: xenial
      name: "Ubuntu 16.04 with Qt5"
      addons:
        apt:
          packages:
            - qtbase5-dev
    - os: osx
      name: "MacOS with Qt5"
      addons:
        homebrew:
          packages:
            - libQt5Core-devel
            - libqt5-qtbase-common-devel


